# Generated by Django 4.2 on 2024-03-13 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessControlType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Pending'), ('G', 'Granted'), ('D', 'Denied')], default='P', max_length=1)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('path', models.CharField(max_length=255, unique=True)),
                ('method', models.CharField(blank=True, max_length=6, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoints', models.ManyToManyField(related_name='user_profiles', through='myview.AccessRequest', to='myview.endpoint')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='endpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myview.endpoint'),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myview.userprofile'),
        ),
        migrations.CreateModel(
            name='EndpointPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('can_access', models.BooleanField(default=False)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myview.endpoint')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myview.userprofile')),
            ],
            options={
                'verbose_name': 'Endpoint Permission',
                'verbose_name_plural': 'Endpoint Permissions',
                'unique_together': {('user_profile', 'endpoint')},
            },
        ),
        migrations.CreateModel(
            name='EndpointAccessControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('access_control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myview.accesscontroltype')),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myview.endpoint')),
            ],
            options={
                'unique_together': {('endpoint', 'access_control')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='accessrequest',
            unique_together={('user_profile', 'endpoint')},
        ),
    ]
