# Generated by Django 4.2.11 on 2024-04-17 15:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ADGroupAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('cn', models.CharField(max_length=255, verbose_name='Common Name')),
                ('canonical_name', models.CharField(max_length=1024)),
                ('distinguished_name', models.CharField(max_length=1024)),
                ('members', models.ManyToManyField(related_name='ad_group_members', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ADOrganizationalUnitAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('distinguished_name', models.CharField(max_length=1024)),
                ('members', models.ManyToManyField(related_name='ad_organizational_unit_members', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('path', models.CharField(max_length=255, unique=True)),
                ('method', models.CharField(blank=True, default='', max_length=6)),
                ('ad_groups', models.ManyToManyField(blank=True, related_name='endpoints', to='myview.adgroupassociation')),
                ('ad_organizational_units', models.ManyToManyField(blank=True, related_name='endpoints', to='myview.adorganizationalunitassociation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
