# Generated by Django 4.2.11 on 2024-04-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='ad_organizational_units',
            field=models.ManyToManyField(blank=True, related_name='endpoints', to='myview.adorganizationalunitassociation'),
        ),
    ]
