# Generated by Django 4.2.11 on 2024-04-01 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='ad_groups',
            field=models.ManyToManyField(blank=True, related_name='endpoints', to='myview.adgroupassociation'),
        ),
    ]
