# Generated by Django 4.2.11 on 2024-04-12 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myview', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('resource_path', models.CharField(max_length=1024, unique=True)),
                ('ad_groups', models.ManyToManyField(related_name='resources', to='myview.adgroupassociation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
