# Generated by Django 4.2 on 2024-02-20 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myview', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accessrequest',
            unique_together={('user_profile', 'organizational_unit')},
        ),
    ]
