# Generated by Django 4.2.11 on 2024-04-12 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myview', '0002_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='resource_path',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
