# Generated by Django 4.2 on 2024-02-19 14:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myview', '0002_endpointaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationalunit',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizationalunit',
            name='datetime_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
