# Generated by Django 4.2 on 2024-03-11 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myview', '0002_alter_accessrequest_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EndpointAccess',
        ),
    ]
