# Generated by Django 4.2 on 2024-02-19 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myview', '0003_organizationalunit_datetime_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizationalunit',
            old_name='name',
            new_name='distinguished_name',
        ),
    ]
