# Generated by Django 4.2.11 on 2024-04-15 10:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myview', '0003_alter_resource_resource_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adgroupassociation',
            name='members',
            field=models.ManyToManyField(related_name='ad_group_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ADOrganizationalUnitAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('distinguished_name', models.CharField(max_length=1024)),
                ('members', models.ManyToManyField(related_name='ad_organizational_unit_members', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
