# Generated by Django 4.2 on 2024-03-11 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myview', '0003_delete_endpointaccess'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('path', models.CharField(max_length=255, unique=True)),
                ('method', models.CharField(blank=True, max_length=6, null=True)),
                ('organizational_units', models.ManyToManyField(blank=True, related_name='endpoints', to='myview.organizationalunit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('G', 'Granted'), ('D', 'Denied')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ous',
            field=models.ManyToManyField(related_name='user_profiles', through='myview.AccessRequest', to='myview.organizationalunit'),
        ),
        migrations.CreateModel(
            name='EndpointPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('can_access', models.BooleanField(default=False)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myview.endpoint')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myview.userprofile')),
            ],
            options={
                'unique_together': {('user_profile', 'endpoint')},
            },
        ),
    ]
