# Generated by Django 4.2 on 2024-02-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myview', '0004_rename_name_organizationalunit_distinguished_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationalunit',
            name='canonical_name',
            field=models.TextField(default=' ', unique=True),
            preserve_default=False,
        ),
    ]
