# Generated by Django 4.2 on 2024-03-11 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myview', '0004_endpoint_alter_accessrequest_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessControlType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EndpointOrganizationalUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myview.endpoint')),
                ('organizational_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myview.organizationalunit')),
            ],
            options={
                'unique_together': {('endpoint', 'organizational_unit')},
            },
        ),
        migrations.CreateModel(
            name='EndpointAccessControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('access_control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myview.accesscontroltype')),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myview.endpoint')),
            ],
            options={
                'unique_together': {('endpoint', 'access_control')},
            },
        ),
        migrations.AddField(
            model_name='endpoint',
            name='access_controls',
            field=models.ManyToManyField(blank=True, related_name='endpoints', through='myview.EndpointAccessControl', to='myview.accesscontroltype', verbose_name='Custom Access Controls'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='organizational_units',
            field=models.ManyToManyField(blank=True, related_name='endpoints', through='myview.EndpointOrganizationalUnit', to='myview.organizationalunit'),
        ),
    ]
