# Generated by Django 4.2 on 2024-02-19 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myview', '0005_organizationalunit_canonical_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationalunit',
            name='canonical_name',
        ),
    ]
