# Generated by Django 4.2 on 2024-02-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myview', '0006_remove_organizationalunit_canonical_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationalunit',
            name='canonical_name',
            field=models.TextField(default='', unique=True),
        ),
    ]
