version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"  # The root directory
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/another-directory-to-monitor"  # Another directory you want to monitor
    schedule:
      interval: "weekly"
