services:
  web:
    # Settings for running behind a TLS-terminating proxy (production-like)
    environment:
      DJANGO_DEBUG: "false"
      # Keep cookies secure since clients connect via HTTPS to the proxy
      DJANGO_SESSION_COOKIE_SECURE: "true"
      DJANGO_CSRF_COOKIE_SECURE: "true"
      # Do not force HTTPS at the app layer (proxy already handles it)
      DJANGO_SECURE_SSL_REDIRECT: "false"
      # Keep HSTS enabled if your proxy serves HTTPS to clients
      DJANGO_SECURE_HSTS_SECONDS: "3600"
      DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS: "true"
      DJANGO_SECURE_HSTS_PRELOAD: "true"
      # Allow your public host and localhost during testing
      DJANGO_ALLOWED_HOSTS: "api.security.ait.dtu.dk,localhost,127.0.0.1"
      # Trust the public HTTPS origin and optional local HTTPS if your proxy exposes it
      DJANGO_CSRF_TRUSTED_ORIGINS: "https://api.security.ait.dtu.dk,https://localhost:8121,https://127.0.0.1:8121"
      # Ensure Django honors X-Forwarded-Proto from the proxy (already set in settings)
      # SECURE_PROXY_SSL_HEADER is configured in settings.py
      # MSAL callback used during OAuth flows
      AZURE_REDIRECT_URI: "https://api.security.ait.dtu.dk/auth/callback"
