services:
  web:
    # Local HTTP overrides for convenient dev with prod-like behavior
    environment:
      DJANGO_DEBUG: "false"
      DJANGO_SESSION_COOKIE_SECURE: "false"
      DJANGO_CSRF_COOKIE_SECURE: "false"
      DJANGO_SECURE_SSL_REDIRECT: "false"
      DJANGO_SECURE_HSTS_SECONDS: "0"
      DJANGO_CSRF_TRUSTED_ORIGINS: "http://localhost:8121,http://127.0.0.1:8121,https://localhost:8121,https://127.0.0.1:8121"
      DJANGO_CSRF_COOKIE_DOMAIN: ""
      DJANGO_ALLOWED_HOSTS: "localhost,127.0.0.1,api.security.ait.dtu.dk"
      AZURE_REDIRECT_URI: "http://localhost:8121/auth/callback"
    volumes:
      # Mount local source to override image code at runtime
      - ./app-main:/app/app-main

