services:
  hello:
    container_name: hello-test
    image: nginx:alpine
    restart: unless-stopped
    networks:
      - internal
    ports:
      - "1234:80"
    volumes:
      - ./hello-world.html:/usr/share/nginx/html/index.html:ro

networks:
  internal:
    external: true
