# Generated by Django 4.2.11 on 2024-03-19 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myview', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationalUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('distinguished_name', models.TextField(unique=True)),
                ('canonical_name', models.TextField(default='', unique=True)),
            ],
            options={
                'ordering': ['canonical_name'],
                'abstract': False,
            },
        ),
    ]
