# Generated by Django 4.2.11 on 2024-03-19 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myview', '0002_organizationalunit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='endpoints',
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('members', models.ManyToManyField(related_name='groups', to='myview.userprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='endpointpermission',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='endpointpermission',
            name='user_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myview.usergroup'),
        ),
        migrations.AlterUniqueTogether(
            name='endpointpermission',
            unique_together={('user_group', 'endpoint')},
        ),
        migrations.RemoveField(
            model_name='endpointpermission',
            name='user_profile',
        ),
    ]
