# Generated by Django 4.2.11 on 2024-03-19 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myview', '0003_remove_userprofile_endpoints_usergroup_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accessrequest',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='user_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myview.usergroup'),
        ),
        migrations.AlterUniqueTogether(
            name='accessrequest',
            unique_together={('user_group', 'endpoint')},
        ),
        migrations.RemoveField(
            model_name='accessrequest',
            name='user_profile',
        ),
    ]
