FROM python:3.10

RUN mkdir -p /usr/src/project

WORKDIR /usr/src/project

RUN apt-get update && apt-get install -y unixodbc


##### microsoft
RUN echo "deb [arch=amd64] https://packages.microsoft.com/debian/10/prod buster main" > /etc/apt/sources.list.d/microsoft-prod.list
#### RUN apt update
RUN wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
RUN mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg
RUN apt update && ACCEPT_EULA=Y apt-get install -y msodbcsql18
#### RUN ACCEPT_EULA=Y apt-get install -y msodbcsql18
