version: '3.8'

services:
  api-security-ait-dtu-dk:
    build:
      context: .
      dockerfile: Dockerfile-api-security-ait-dtu-dk
    image: vicmrp/api-security-ait-dtu-dk
    container_name: app
    restart: unless-stopped
    tty: true
    volumes:
      - ..:/usr/src/project
    