version: '3.8'

# development command
# docker-compose -p dev-api-security-ait-dtu-dk -f ./my-development-docker-compose.yaml up -d
# production command
# docker-compose -p prod-api-security-ait-dtu-dk -f ./my-production-docker-compose.yaml up -d
services:
  xx-api-security-ait-dtu-dk-app-main:
    command: bash -c "cd /usr/src/project/app-main && source /usr/src/venvs/app-main/bin/activate && python3 manage.py runserver 0.0.0.0:8121"
    image: vicre/api-security-ait-dtu-dk-app-main:python-3.10-bullseye-django-4.2.x-18-03-2024-venv-myversion-1.0.1 # latest pip packages on date 18-03-2024
    restart: always
    tty: true
    volumes:
      - ..:/usr/src/project
      - ../shared-project-data:/mnt/shared-project-data
    networks:
      - shared_network

  xx-api-security-ait-dtu-dk-httpd-service:
    restart: always
    image: vicre/api-security-ait-dtu-dk-httpd-service:httpd-2.4
    volumes:
      - ../shared-project-data:/mnt/shared-project-data
      - ../httpd-service/data/virtualhosts:/usr/local/apache2/conf/virtualhosts
      - ../httpd-service/data/httpd.conf:/usr/local/apache2/conf/httpd.conf
    networks:
      - shared_network

  xx-api-security-ait-dtu-dk-mariadb-service:
    image: mariadb:latest
    restart: always
    environment:
      PMA_HOST: ${MYSQL_HOST} # beta-api-security-ait-dtu-dk-mariadb-service
      MYSQL_ROOT_PASSWORD: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - beta-api-security-ait-dtu-dk-mariadb-service-volume:/var/lib/mysql
      - ../mariadb-service/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - shared_network

  xx-api-security-ait-dtu-dk-phpmyadmin-service:
      image: phpmyadmin/phpmyadmin:latest
      restart: always
      ports:
        - "5010:80"
      environment:
        PMA_HOST: ${MYSQL_HOST} # beta-api-security-ait-dtu-dk-mariadb-service
        MYSQL_ROOT_PASSWORD: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      volumes:
        - ../phpmyadmin-service/phpmyadmin-misc.ini:/usr/local/etc/php/conf.d/phpmyadmin-misc.ini
      networks:
        - shared_network

networks:
  shared_network:
    external: true

volumes:
  beta-api-security-ait-dtu-dk-mariadb-service-volume:
    external: true
