version: '3.8'
services:
  xx-api-security-ait-dtu-dk-app-main:
    image: vicre/api-security-ait-dtu-dk-app-main:python-3.10-bullseye-django-4.2.11-27-03-2024-venv-myversion-1.0.3
    restart: always
    tty: true
    volumes:
    - ..:/usr/src/project
    - ../shared-project-data:/mnt/shared-project-data
    networks:
    - shared_network
    command: '"bash -c \"cd /usr/src/project/app-main && source /usr/src/venvs/app-main/bin/activate
      && python3 manage.py runserver 0.0.0.0:8121\""'
  xx-api-security-ait-dtu-dk-httpd-service:
    image: vicre/api-security-ait-dtu-dk-httpd-service:httpd-2.4
    volumes:
    - ../shared-project-data:/mnt/shared-project-data
    - ../httpd-service/data/virtualhosts:/usr/local/apache2/conf/virtualhosts
    - ../httpd-service/data/httpd.conf:/usr/local/apache2/conf/httpd.conf
    networks:
    - shared_network
  xx-api-security-ait-dtu-dk-mariadb-service:
    image: mariadb:11.3.2
    restart: always
    environment:
      PMA_HOST: ${MYSQL_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
    - beta-api-security-ait-dtu-dk-mariadb-service-volume:/var/lib/mysql
    - ../mariadb-service/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
    - shared_network
  xx-api-security-ait-dtu-dk-phpmyadmin-service:
    image: phpmyadmin/phpmyadmin:5.2.1
    restart: always
    ports:
    - 5010:80
    environment:
      PMA_HOST: ${MYSQL_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
    - ../phpmyadmin-service/phpmyadmin-misc.ini:/usr/local/etc/php/conf.d/phpmyadmin-misc.ini
    networks:
    - shared_network
networks:
  shared_network:
    external: true
volumes:
  beta-api-security-ait-dtu-dk-mariadb-service-volume:
    external: true
