#!/bin/bash

# example usage 
# ./mydockerbuild api-security-ait-dtu-dk-app-main:python-3.12-bullseye

# Check if an argument was provided
if [ "$#" -ne 1 ]; then
    echo "Usage: $0 foldername:name-tag"
    exit 1
fi

# Extract folder name, image name, and tag from the argument
FOLDER_NAME=$(echo $1 | cut -d ':' -f 1)
IMAGE_NAME=$(echo $FOLDER_NAME | sed 's/-/\//g')
TAG=$(echo $1 | cut -d ':' -f 2)

echo $FOLDER_NAME; 
echo $IMAGE_NAME;
echo $TAG;
exit 1

# Navigate to the specified folder
cd "$(dirname "$0")" || exit
if [ ! -d "../$FOLDER_NAME" ]; then
    echo "The specified folder does not exist."
    exit 1
fi

cd "../$FOLDER_NAME" || exit

# Build the Docker image
echo "Building Docker image: vicre/$IMAGE_NAME:$TAG..."
docker build -t vicre/"$IMAGE_NAME":"$TAG" .

# Check if the build was successful
if [ $? -eq 0 ]; then
    echo "Docker image vicre/$IMAGE_NAME:$TAG successfully built."
else
    echo "Failed to build the Docker image."
    exit 1
fi
