# Generated by Django 4.2 on 2023-12-15 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_mod', '0004_auto_20231215_2100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customtoken',
            options={'verbose_name': 'MyToken', 'verbose_name_plural': 'MyTokens'},
        ),
    ]
