# Generated by Django 4.2 on 2024-01-26 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_mod', '0007_customtoken_extended_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtoken',
            name='extended_key',
        ),
    ]
