# Generated by Django 4.2 on 2024-03-12 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myview', '0005_accesscontroltype_endpointorganizationalunit_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='endpointorganizationalunit',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='endpointorganizationalunit',
            name='endpoint',
        ),
        migrations.RemoveField(
            model_name='endpointorganizationalunit',
            name='organizational_unit',
        ),
        migrations.AlterUniqueTogether(
            name='endpointpermission',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='endpointpermission',
            name='endpoint',
        ),
        migrations.RemoveField(
            model_name='endpointpermission',
            name='user_profile',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='ous',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='endpoint',
            name='organizational_units',
        ),
        migrations.DeleteModel(
            name='AccessRequest',
        ),
        migrations.DeleteModel(
            name='EndpointOrganizationalUnit',
        ),
        migrations.DeleteModel(
            name='EndpointPermission',
        ),
        migrations.DeleteModel(
            name='OrganizationalUnit',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
