# Generated by Django 4.2 on 2023-09-18 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_meta', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
