# Generated by Django 4.2 on 2023-12-15 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_mod', '0003_initial'),
    ]

    operations = [
    ]
