# Generated by Django 4.2 on 2023-12-15 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_mod', '0005_alter_customtoken_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customtoken',
            options={'verbose_name': 'Custom Token', 'verbose_name_plural': 'Custom Tokens'},
        ),
    ]
