# Generated by Django 4.2 on 2023-12-21 21:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_mod', '0006_alter_customtoken_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtoken',
            name='extended_key',
            field=models.CharField(db_index=True, default=django.utils.timezone.now, max_length=128, unique=True, verbose_name='Extended Key'),
            preserve_default=False,
        ),
    ]
